import { invoke } from "@tauri-apps/api/core";
import type { CommandExecResult } from "@/core/agent/agentLoop";

/**
 * Hermoz Studio's Stitch integration.
 *
 * Stitch (design.google/stitch) is Google's AI UI-design tool. It ships a
 * real SDK — `@google/stitch-sdk` — that wraps its official MCP server, so
 * this is a genuine integration, not a simulation: Hermoz shells out to a
 * tiny Node bridge script that calls the real SDK and hands back exactly
 * the HTML Stitch generated.
 *
 * The bridge lives inside the *user's* workspace (under `.hermoz/`) rather
 * than Hermoz's own install directory, since `execute_workspace_command`
 * only runs commands inside the configured workspace folder. It's
 * provisioned lazily, the first time a `generate_ui` action runs.
 *
 * Requires the user to set STITCH_API_KEY in their environment (see
 * https://github.com/google-labs-code/stitch-sdk) — Hermoz doesn't (and, for
 * a Google Cloud-backed key, can't cleanly) manage that secret itself.
 */

const PACKAGE_JSON = `{
  "name": "hermoz-stitch-bridge",
  "private": true,
  "type": "module",
  "dependencies": {
    "@google/stitch-sdk": "latest"
  }
}
`;

// Kept as a template string (not a checked-in .mjs file) so it ships as part
// of the Hermoz app bundle itself and gets (re)written into any workspace on
// first use — no separate asset to lose track of.
const BRIDGE_SCRIPT = `// Auto-generated by Hermoz Studio. Safe to delete — it's rewritten on demand.
// Wraps @google/stitch-sdk so Hermoz's agent loop can call Stitch through a
// plain child process (reusing the same approved "command" execution path
// as everything else Hermoz runs).
import { readFile } from "node:fs/promises";
import { stitch } from "@google/stitch-sdk";

async function main() {
  const argsPath = process.argv[2];
  if (!argsPath) {
    console.log(JSON.stringify({ error: "No args file path given." }));
    process.exit(1);
  }

  let args;
  try {
    args = JSON.parse(await readFile(argsPath, "utf-8"));
  } catch (e) {
    console.log(JSON.stringify({ error: \`Couldn't read args file: \${e.message}\` }));
    process.exit(1);
  }

  if (!process.env.STITCH_API_KEY) {
    console.log(
      JSON.stringify({
        error:
          "STITCH_API_KEY is not set. Get a key from Google Stitch (design.google/stitch) and set it as an environment variable before running Hermoz.",
      }),
    );
    process.exit(1);
  }

  try {
    // One Stitch project per workspace, reused across calls so related
    // screens stay grouped together in Stitch's own project view.
    //
    // NOTE: the SDK's public README (github.com/google-labs-code/stitch-sdk)
    // documents \`project.generate(prompt)\` for creating a screen, and
    // separately says Stitch "supports editing existing screens" via its
    // MCP tools, but doesn't spell out that edit method's exact name in the
    // README itself. This bridge currently always calls \`generate()\` — for
    // a true in-place edit (rather than a new screen each time), check
    // \`await stitch.callTool("list_tools", {})\` (or the SDK's TypeScript
    // types) for the exact edit tool name and wire it in here.
    const projectId = args.projectId || "hermoz-workspace";
    let project;
    try {
      project = stitch.project(projectId);
    } catch {
      project = null;
    }
    if (!project) {
      const created = await stitch.callTool("create_project", { title: projectId });
      project = stitch.project(created.projectId || projectId);
    }

    const screen = await project.generate(args.prompt);
    const htmlUrl = await screen.getHtml();
    const res = await fetch(htmlUrl);
    if (!res.ok) {
      console.log(JSON.stringify({ error: \`Failed to download generated HTML (HTTP \${res.status}).\` }));
      process.exit(1);
    }
    const html = await res.text();
    console.log(JSON.stringify({ html, projectId, screenId: screen.id || null }));
  } catch (e) {
    console.log(JSON.stringify({ error: e?.message || String(e) }));
    process.exit(1);
  }
}

main();
`;

export interface EnsureBridgeResult {
  ok: boolean;
  log: string;
}

/**
 * Ensures `.hermoz/stitch-bridge.mjs` and its one dependency exist in the
 * given workspace, installing the SDK the first time it's needed. Cheap to
 * call every time — the dependency check is a single file read.
 */
export async function ensureStitchBridgeReady(workspace: string): Promise<EnsureBridgeResult> {
  const depInstalled = await invoke<string>("read_workspace_file", {
    workspace,
    path: ".hermoz/node_modules/@google/stitch-sdk/package.json",
  })
    .then(() => true)
    .catch(() => false);

  if (!depInstalled) {
    await invoke("write_workspace_file", {
      workspace,
      path: ".hermoz/package.json",
      content: PACKAGE_JSON,
    });
    const install = await invoke<CommandExecResult>("execute_workspace_command", {
      command: "npm install",
      cwd: ".hermoz",
      workspace,
    });
    if (install.exitCode !== 0) {
      return { ok: false, log: install.stderr || install.stdout || "npm install failed." };
    }
  }

  await invoke("write_workspace_file", {
    workspace,
    path: ".hermoz/stitch-bridge.mjs",
    content: BRIDGE_SCRIPT,
  });

  return { ok: true, log: "Stitch bridge ready." };
}
